# baseURL = "http://brain.how/"
baseURL = "/"
languageCode = "en-us"
title = "Brain Awareness Week"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Mark Beenhakker"
    description = "The University of Virginia's neuroscience outreach program"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    # font = "Raleway" # should match the name on Google Fonts!
    font = "Trocchi"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/materials/"
    name = "Materials"
    weight = 2

# [[menu.main]]
#     url = "/calendar/"
#     name = "Calendar"
#     weight = 3

# [[menu.main]]
#     url = "/pictures/"
#     name = "Pictures"
#     weight = 4

# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 5

# [[menu.main]]
#     url = "/post/"
#     name = "Posts"
#     weight = 6

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
#   Only the icons up to version 4.7.0 are available

[[menu.icon]]
    url = "mailto:blab@virginia.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/blabuva/Website_BAW"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "http://neurograd.virginia.edu/"
    name = "info"
    weight = 3

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "twitter"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "linkedin"
#     weight = 5

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 6
